[package]
name = "rspotify_hyper"
version = "0.2.0"
edition = "2018"
authors = ["Andrzej Ressel <jereksel@gmail.com>"]
description = "Rspotify login using hyper.rs http server"
license = "MIT"

[dependencies]
rspotify = "0.4.0"
hyper = "0.12.29"
futures = "0.1.27"
webbrowser = "0.5.1"
